// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	thing "ahobson/gofutz/thing"

	mock "github.com/stretchr/testify/mock"
)

// Thing is an autogenerated mock type for the Thing type
type Thing struct {
	mock.Mock
}

// FetchThing provides a mock function with given fields: thingInput
func (_m *Thing) FetchThing(thingInput thing.ThingInput) (thing.ThingOutput, error) {
	ret := _m.Called(thingInput)

	var r0 thing.ThingOutput
	if rf, ok := ret.Get(0).(func(thing.ThingInput) thing.ThingOutput); ok {
		r0 = rf(thingInput)
	} else {
		r0 = ret.Get(0).(thing.ThingOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(thing.ThingInput) error); ok {
		r1 = rf(thingInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
